services:

# TODO: hardcodear credenciales db para alumnos
  db:
    image: postgres:16-alpine
    container_name: route_generator_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - route-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: route_generator_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - route-network
  
  #TODO: app port en .env
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: route-generator-api
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - route-network    

volumes:
  pgdata:

networks:
  route-network:
    driver: bridge
